# Generated by Django 6.0.4 on 2026-04-30 18:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('brazos', 'Brazos'), ('hombros', 'Hombros'), ('cardio', 'Cardio'), ('fullbody', 'Full Body')], max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='routines/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
